version: "3.9"
    
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
volumes:
  db_data: {}
  wordpress_data: {}