version: 1

containers: 
  - mytest-container:
      volumes:
        - volume:
            from: test/
            to: /var/www/html/
            mode: 775
            owner: www-data:www-data
            cmd: 
              - echo hi
            ignore:
              - node_modules/
            replace:
              - "string:string"
        - volume:
            profile: local
            from: test/config.php
            to: /var/www/html/config.php
            mode: 775
            owner: www-data:www-data
            cmd: 
              - echo hi
            ignore:
              - node_modules/
            replace:
              - "string:string"
        - volume:
            profile: staging
            from: test/config.php
            to: /var/www/html/config.php
            mode: 775
            owner: www-data:www-data
            cmd: 
              - echo hi
            ignore:
              - node_modules/
            replace:
              - "string:string"